name = "marketplace-handler"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[observability.logs]
enabled = true

[vars]
API_BASE_URL = "https://portal.ieeetamu.org"

[env.dev.vars]
API_BASE_URL = "http://localhost:4000"
